Updates for PyPI Publish [minor] (#62)
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/try-setup-install.yml b/.github/workflows/try-setup-install.yml
--- a/.github/workflows/try-setup-install.yml
+++ b/.github/workflows/try-setup-install.yml
@@ -1,3 +1,7 @@
+# For most recent version see:
+# https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/try-setup-install.yml
+# Copy any updates to wipac-dev-tools.
+
 name: Try Setup Install
 
 on: [push]
@@ -13,9 +17,15 @@ jobs:
       - name: Python Versions
         id: py3_versions
         run: |
-          minmin_maxmax=$(grep -P "\(\(\d+, ?\d+\), ?\(\d+, ?\d+\)\)" -oh setup.py | sed 's/[^0-9]/ /g')
+          pys=`grep -P "python_requires = >=\d+.\d+, <\d+.\d+" -oh setup.cfg` # exits if missing
+          minmin_maxmax=`echo "$pys" | sed 's/[^0-9]/ /g'`
+          echo $minmin_maxmax
+          if [ -z "$minmin_maxmax" ]; then
+            echo "could not retrieve 'python_requires' from 'setup.cfg'"
+            exit 1
+          fi
           IFS=', ' read -r -a array <<< "$minmin_maxmax"
-          min_thru_max_series=$(for i in `seq ${array[1]} ${array[3]}`; do printf "'3.$i',"; done | rev | cut -c 2- | rev)
+          min_thru_max_series=$(for i in `seq ${array[1]} $((array[3]-1))`; do printf "'3.$i',"; done | rev | cut -c 2- | rev)
           echo ::set-output name=matrix::{\"py3_versions\":[$(echo $min_thru_max_series)]}\"
           echo $min_thru_max_series
 
